bot:
  token: "${BOT_TOKEN}"  # подтягивается из .env
  base_save_path: "C:/Users/User/PycharmProjects/pythonProject4"

limits:
  max_file_size_mb: 50
  docx_lines_per_page: 30

logging:
  level: "INFO"
